@root = https://localhost:7128

GET {{root}}/theme
Accept: application/json

###

GET {{root}}/set?themeId=1
Accept: application/json

###

GET {{root}}/set/42005-1
Accept: application/json

###

GET {{root}}/inventory/9435
Accept: application/json
