@root = https://localhost:7128

### Get all themes

GET {{root}}/theme
Accept: application/json

### Get sets by theme

GET {{root}}/set?themeId=1
Accept: application/json

### Get set by set number

GET {{root}}/set/42005-1
Accept: application/json

### Get set inventory by set id

GET {{root}}/inventory/9435
Accept: application/json

### Get all colors

GET {{root}}/color
Accept: application/json

### Get color by id

GET {{root}}/color/379
Accept: application/json

### Create color

POST {{root}}/color
Content-Type: application/json
Accept: application/json

{
  "name": "http-test",
  "rgb": "0F0F0F",
  "isTransparent": false
}

### Update color

PUT {{root}}/color/12842
Content-Type: application/json
Accept: application/json

{
  "name": "update-test",
  "rgb": "010101",
  "isTransparent": true
}

### Delete color

DELETE {{root}}/color/12750
Accept: application/json

